<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="159045" started-at="2017-05-25T09:14:43Z" finished-at="2017-05-25T09:17:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="159045" started-at="2017-05-25T09:14:43Z" finished-at="2017-05-25T09:17:22Z">
      <class name="iosTest.LoginTest1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:iosTest.LoginTest1@2a17b7b6]" name="setUp" is-config="true" duration-ms="59916" started-at="2017-05-25T17:14:43Z" finished-at="2017-05-25T17:15:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginFaildTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:iosTest.LoginTest1@2a17b7b6]" name="loginFaildTest" duration-ms="98536" started-at="2017-05-25T17:15:43Z" description="登陆成功" data-provider="LoginSucess" finished-at="2017-05-25T17:17:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[爱学派FF]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[a11111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9.3.3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [请选择上课班级] but found [请选择上课班级1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [请选择上课班级] but found [请选择上课班级1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at iosTest.LoginTest1.loginFaildTest(LoginTest1.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFaildTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:iosTest.LoginTest1@2a17b7b6]" name="tearDown" is-config="true" duration-ms="561" started-at="2017-05-25T17:17:22Z" finished-at="2017-05-25T17:17:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- iosTest.LoginTest1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
